apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: resource-injector-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: resource-injector-service-account
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: resource-injector-access-role
  apiGroup: rbac.authorization.k8s.io
